steps:

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Apply deployment
- name: "gcr.io/cloud-builders/kubectl"
  args: ["apply", "-f", "myapp.yaml"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_DEPLOYMENTNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  #  - 'namespace/${_NAMESPACENAME}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. 
    _PROJECT: akcess-labs
    _ZONE: europe-west2-a
    _GKE_CLUSTER: akcess
    
    #Repository Specific configuration. 
    _DEPLOYMENTNAME: myapp
    _CONTAINERNAME: myapp  
    _REPO_NAME: ci-cd-deployment
   # _NAMESPACENAME: test-deployment
    
    # Developers ONLY change
    _VERSION: v1.01
    
options:
    substitution_option: 'ALLOW_LOOSE'

