steps:

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: akcess-labs
    _ZONE: europe-west2-a
    _GKE_CLUSTER: akcess
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: ravi-deployment1
    _CONTAINERNAME: nginx:latest    
    _REPO_NAME: ci-cd-deployment
    
    # Developers ONLY change
    _VERSION: v1.01
    
options:
    substitution_option: 'ALLOW_LOOSE'

